# -*- coding: utf-8 -*-
"""week1_assignment.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RKnrT5MBjpGPAEjqB5SvzbWlD1sd3Rc4
"""

#convert an integer to a string
i=9
print(i,type(i))
i=str(i)
print(i,type(i))

#convert a string to an integer
x="1000"
print(x,type(x))
x=int(x)
print(x,type(x))

#convert a float to an integer
y=9.892
print(y,type(y))
y=int(y)
print(y,type(y))

#convert a string to a float
s="9087"
print(s,type(s))
s=float(s)
print(s,type(s))

#convert an integer to a float
j=90
print(j,type(j))
j=float(j)
print(j,type(j))