# -*- coding: utf-8 -*-
"""Week4_assignment.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8pXnmSQ-SArA-Tld8yqbD44wHuTIYzr
"""

#Read in a CSV file
import csv 
# opening the CSV file
with open('k.csv', mode ='r')as file:
   
  # reading the CSV file
  csvFile = csv.reader(file)
 
  # displaying/parse the contents of the CSV file
  for lines in csvFile:
        print(lines)

  file.close()

#Write the data back to a CSV file
import csv 
    
# field names 
fields = ['P_Id', 'P_Name', 'Quantity', 'Price(RS.)'] 
    
# data rows of csv file 
rows = [ [89,'Screw Driver',25,50],
         [90,'Hammer',80,200],
         [56,'Cutter',80,60],
        [58,'Screws',1000,10]
        ] 
    
# name of csv file 
filename = "enterprise.csv"
    
# writing to csv file 
with open(filename, 'w') as csvfile: 
    # creating a csv writer object 
    csvwriter = csv.writer(csvfile) 
        
    # writing the fields 
    csvwriter.writerow(fields) 
        
    # writing the data rows 
    csvwriter.writerows(rows)

#Split a CSV file based on a filtering criteria (for example all the rows containing a certain word in a certain column)
with open(filename,'r') as csvfile:

  # reading the CSV file
  csvFile = csv.reader(csvfile)
 
  # displaying/parse the contents of the CSV file
  for lines in csvFile:
    if (lines[2] == '80'):
           print(lines)

#Read a CSV file with name, number, street, city, state, pin and create a new file containing state, city,number of houses in the state/city into another CSV file?
import csv 
    
# field names 
fields = ['name','number','street','city','state','pin'] 
    
# data rows of csv file 
rows = [ ['lokesh','99','R.K.street','chennai','Tamil nadu','600087'],
        ['rajesh','88','M.N.street','kaveri','Tamil nadu','600085'],
        ['priya','97','k.k.Street','Bangalore','Karnataka','900087'],
        ] 
    
# name of csv file 
filename = "student.csv"
    
# writing to csv file 
with open(filename, 'w') as csvfile: 
    # creating a csv writer object 
    csvwriter = csv.writer(csvfile) 
        
    # writing the fields 
    csvwriter.writerow(fields) 
        
    # writing the data rows 
    csvwriter.writerows(rows)

with open(filename, 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    fields = next(csvreader)
    rows=[]
    for i in csvreader:
      rows.append(i)
   
   fname="SubStudent.csv" 
   with open(fname, 'w') as new_file:
        field=['state','city','number']
        cwriter = csv.writer(new_file)
        cwriter.writerow(field)
        for item in range(len(rows)):    
            cwriter.writerow((rows[item][4],rows[item][3],rows[item][1]))